### ISSUE TITLE
Install issue (constants.py not found)

### ISSUE THREAD

**Issue by asberk** [Teque5/pydymax#1]
I'm following the install instructions and receiving this error, even though constants.py resides in the same directory as **init**.py. 
Do you know how to solve this issue? 

> File "../setup.py", line 4, in <module>
>     from dymax import **version**
>   File "//marsdymax/pydymax/dymax/**init**.py", line 6, in <module>
>     from constants import *
> ImportError: No module named 'constants'

**Comment by Teque5** [comment]
Hey there.

When I wrote the setup.py way back when I wasn't super knowledgeable about the python packaging process using setuptools. For a long time i've been meaning to fix the installer and i've bumped it up my to-do list. In the meantime most of the functionality can be had by simply cloning the repo and operating in the /dymax directory.

I'll leave this issue open until I fix things.

**Comment by Teque5** [comment]
If you clone everything and run `python examples.py` then everything will run. I just did this on a fresh machine. I did have to add a missing slash though... I'll fix it in a minute.

`data_directory = current_directory + '/../data-rect/'`
should be
`data_directory = current_directory + os.sep + '..'+os.sep+'data-rect'+os.sep`
on line 20

**Comment by Teque5** [comment]
fixed in develop
