### ISSUE TITLE
How to integrate the WSG84 coordinate system?

### ISSUE THREAD

**Issue by amillscampisi** [Teque5/pydymax#2]
I would like to contribute to this project by helping add the WSG84 coordinate system, but I don't know what that would look like. Is there any kind of reference or do you know what the algorithm would be? I am assuming that you would start by projecting the boundaries of the triangles from the icosahedron onto the inside of the ellipsoid, but I am not sure if that is the right way to start.

**Comment by Teque5** [comment]
Okay I thought a bit about this today. So as it stands it works like this:
> (lon, lat) -> (theta, phi) -> (X, Y, Z) -> (X,Y)
> wgs84 -> spherical -> cartesian -> dymaxion

A better more accurate way to do this would be to go:
> (lon, lat) -> (X, Y, Z) -> (X, Y)
> wgs84 -> ECEF -> dymaxion

And there are many published methods to go from wgs84 to earth-centered-earth-fixed accurately. I wrote a method but I can't find it right now. I know that the `pyproj` and `cartopy` modules have this functionality.

Another separate way you could help would be to create a method that goes from dymaxion back to ecef or wgs84.
