### ISSUE TITLE
np.linspace rounding input in convert_rectimage_2_dymaximage

### ISSUE THREAD

**Issue by bnlcas** [Teque5/pydymax#5]
I recently downloaded this module and I ran into an issue with `examples.py`:
The function `convert_rectimage_2_dymaximage` throws an error due to the inputs given to `np.linspace`:
`'float' object cannot be interpreted as an integer`.
On line 278, `for i, lon in enumerate(np.linspace(-180, 180, xsize/speedup, endpoint=True))` has a problem if `xsize/speedup` is not an integer. Similarly on line 283, the linspace function throws an error is the number of points is not an integer. 

Changing these two lines use `int(xsize/speedup)` and ` int(ysize/speedup)` as the number of points in linspace fixed the problem for me.

This issue prevented me from running the examples script so I imagine that it is causing issues elsewhere. I would be happy to submit a pull request to patch this.

**Comment by Teque5** [comment]
Took care of that and did a quick cleanup pass simultaneously.

**Comment by bnlcas** [comment]
Awesome! Thanks for the quick response on this issue.
